config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#top'
  get 'home/about' => 'home/about'
  get '/map_request', to: 'images#map', as: 'map/request'
  get 'search' => 'images#index'
  resources :users do
    member do
      get 'check'
      patch 'withdrawl'
    end
  end

  resources :categories, only: [:show]

  resources :inquiries do
    collection do
      get 'confirm'
      get 'thanks'
    end
  end

  resources :images do
    collection do
      get 'favorite'
      get 'access'
    end
    resources :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  namespace :admins do
    get 'home' => 'home#top'
    resources :users

    resources :images do
      resources :comments, only: %i[create destroy]
      resource :favorites, only: %i[create destroy]
    end

    resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :images, dependent: :destroy

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  belongs_to :category
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  is_impressionable counter_cache: true
  default_scope -> { order(created_at: :desc) }

  validates :image, presence: true
  validates :title, presence: true
  validates :caption, presence: true
  validates :address, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def favorited_by?(admin)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      Image.where('title LIKE ?', "%#{search}%")
    else
      Image.all
    end
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  attr_accessor :name, :email, :message

  validates :name, presence: { message: '名前を入力してください' }
  validates :email, presence: { message: 'メールアドレスを入力してください' }
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  enum is_active: { Available: true, Invalid: false }
  # 有効会員はtrue、退会済み会員はfalse

  def active_for_authentication?
    super && (is_active === 'Available')
  end
  # is_activeが有効の場合は有効会員(ログイン可能)

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_images, through: :favorites, source: :image
  attachment :profile_image

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/admins/images_controller.rb
class Admins::ImagesController < ApplicationController
  before_action :authenticate_admin!
  before_action :get_user_and_category, only: %i[new index favorite access show edit]

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id
    if	@image.save
      redirect_to images_path
    else
      @categories = Category.where(active_status: true)
      render :new
    end
  end

  def index
    @images = Image.all
    @images = Image.order(impressions_count: 'DESC').order(created_at: :desc)
    # order(created_at: :desc)=最新投稿順
  end

  def favorite
    @images = Image.all.sort { |a, b| b.favorited_users.count <=> a.favorited_users.count }
  end

  def access
    @images = Image.order(impressions_count: 'DESC')
  end

  def show
    @image = Image.find(params[:id])
    @images = Image.all
    @comment = Comment.new
    impressionist(@image, nil, unique: %i[impressionable_id ip_address])
    # impressionist(@image, nil, unique: [:session_hash])
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if	@image.update(image_params)
      redirect_to image_path(@image)
    else
      @categories = Category.where(active_status: true)
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :address, :title, :latitude, :longitude, :caption, :comment, :category_id)
  end

  def get_user_and_category
    @user = current_user
    @categories = Category.where(active_status: true)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user!, only: %i[create edit update destroy]
  before_action :get_user_and_category, only: %i[new index favorite access show edit]

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id
    if @image.save
      redirect_to images_path
    else
      @categories = Category.where(active_status: true)
      render :new
    end
  end

  def index
    @images = Image.search(params[:search])
    @images = Image.order(impressions_count: 'DESC').order(created_at: :desc)
    # order(created_at: :desc)=最新投稿順
  end

  def favorite
    @images = Image.all.sort { |a, b| b.favorited_users.count <=> a.favorited_users.count }
  end

  def access
    @images = Image.order(impressions_count: 'DESC')
  end

  def show
    @image = Image.find(params[:id])
    @images = Image.all
    @comment = Comment.new
    impressionist(@image, nil, unique: %i[impressionable_id ip_address])
    # impressionist(@image, nil, unique: [:session_hash])
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to image_path(@image)
    else
      @categories = Category.where(active_status: true)
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :address, :title, :latitude, :longitude, :caption, :comment, :category_id)
  end

  def get_user_and_category
    @user = current_user
    @categories = Category.where(active_status: true)
  end

end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/admins/images_helper.rb
module Admins::ImagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camp_sites_helper.rb
module CampSitesHelper
end

app/helpers/campers_helper.rb
module CampersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admins/images/index.html.erb
<main class="clearfix">
    
        <div class="navs">
            <ul class="nav nav-pills nav-justified btn-lg">
                <li role="presentation" class="active"><%= link_to "新着順", images_path %></li>
                <li role="presentation" ><%= link_to "いいね順", favorite_images_path %></li>
                <li role="presentation" ><%= link_to "アクセス数順", access_images_path %></li>
            </ul>
        </div>


    <% @images.each do |image| %>

        <div class="float-content">
            <div class="post-image">
                    <%= link_to admins_image_path(image) do %>
                        <%= attachment_image_tag image, :image, size: "300x300", format: 'jpeg' %>
                    <% end %>
            </div>

            <div class="fct-profile-cont">
                <div class="fct-contents">       
                    <ul>
                        <li class="fct-cont">
                            <% if image.favorited_by?(current_user) %>
                                <%= link_to image_favorites_path(image), method: :delete do %>
                                <i class="fa fa-heart" aria-hidden = "true" style = "color: red;" >
                                    <%= image.favorites.count %>
                                </i>
                                <% end %>                                     
                            <% else %>
                                <%= link_to image_favorites_path(image), method: :post do %>
                                <i class="fa fa-heart-o" aria-hedden = "true" >
                                    <%= image.favorites.count %>
                                </i>
                                <% end %>
                            <% end %>
                        
                                <i class="fa fa-comment-alt" aria-hedden = "true">
                                    <%= image.comments.count %>
                                </i>  

                                <i class="fa fa-eye" aria-hedden = "true">
                                    <%= image.impressions.count %>
                                </i>

                        </li>
                    </ul>
                </div>

                <div class="post-image-title">
                    <%= image.title %>
                </div>

                <div class="acount">
                    <ul>
                        <li class="acount-profile">
                            <i><%= attachment_image_tag(image.user,:profile_image, size: "100x100", class: "img-circle", fallback: "no_image.jpg") %></i>
                        </li>
                        
                        <li class="acount-name">
                            <i><%= image.user.name %></i>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    <% end %>
</main>

app/views/admins/images/show.html.erb
<div class="container">
    <div class="show1 row">
        <h1 class="show-title">投稿詳細</h1>
        <div class="col-sm-7">

            <div class="post-image">
                <%= attachment_image_tag @image, :image, size: "671x300", format: 'jpeg', class: "img-thumbnail" %>
            </div>

            <div class="fct-profile-cont">
                <div class="fct-contents">       
                    <ul>
                        <li class="fct-cont">
                            <% if @image.favorited_by?(current_user) %>
                                <%= link_to image_favorites_path(@image), method: :delete do %>
                                <i class="fa fa-heart" aria-hidden = "true" style = "color: red;" >
                                    <%= @image.favorites.count %>
                                </i>
                                <% end %>                                     
                            <% else %>
                                <%= link_to image_favorites_path(@image), method: :post do %>
                                <i class="fa fa-heart-o" aria-hedden = "true" >
                                    <%= @image.favorites.count %>
                                </i>
                                <% end %>
                            <% end %>
                        
                                <i class="fa fa-comment-alt" aria-hedden = "true">
                                    <%= @image.comments.count %>
                                </i>  

                                <i class="fa fa-eye" aria-hedden = "true">
                                    <%= @image.impressions.count %>
                                </i>

                        </li>
                    </ul>

                    <div class="acount">
                       <table>
                            <tr>
                                <th class="acount-profile">
                                    <td><%= attachment_image_tag(@image.user, :profile_image, size: "80x80", class: "img-circle", fallback: "no_image.jpg") %></td>
                                </th>
                            
                                <th class="acount-name">
                                    <td><%= @image.user.name %></td>
                                </th>
                            </tr>
                        </table>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-sm-5">

            <h3 class="google-map">GoogleMap</h3>

                <div id= 'map'></div>
                <script>
                    let map
                        let geocoder

                        function initMap(){
                          // geocoderを初期化
                          geocoder = new google.maps.Geocoder()
                        　var test ={lat: <%= @image.latitude %>, lng: <%= @image.longitude %>};
                          map = new google.maps.Map(document.getElementById('map'), {
                          center: test,
                          zoom: 8
                          });

                        var marker = new google.maps.Marker({
                                position: test,
                                map: map
                            });
                        }

                </script>
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBITQ4XcXfyuSbyCPHweISwuVjnFLCIV4Y&callback=initMap" async defer></script>

                <table class="table table_noborder">

                    <tr>
                        <th>キャンプ場名</th>
                            <td class="map-address">
                                <%= @image.address %>
                            </td>
                    </tr>

                    <tr>
                        <th>タイトル</th>
                            <td class="title">
                                <%= @image.title %>
                            </td>
                    </tr>

                    <tr>
                        <th>投稿説明</th>
                            <td class="caption">
                                <%= @image.caption %>
                            </td>
                    </tr>

                </table>
                <div class="links">
                    <%= link_to "投稿を編集する", edit_image_path(@image), class: "btn btn-primary btn-block" %> 

                    <%= link_to "投稿を削除する", image_path(@image), class: "btn btn-danger btn-block", method: :delete %>
                </div>

        </div>
    </div>

    <div class="border-row">
        <hr>
    </div>

    <div class="show2 row">
        <div class="comment-contents">
            <h2 class="comment-title">コメント欄</h2>
            <div class="col-sm-7">

                <div class="comment-index">
                    <% @image.comments.each do |comment| %>

                        <table class="comment-index">
                            <tr>
                                <th>
                                    <%= attachment_image_tag comment.user, :profile_image,  size: "100x100", format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                                    <%= comment.user.name %>
                                </th>

                                <td class="comment-text">
                                    <%= comment.comment %>
                                </td>

                                <td class="link">
                                    <% if comment.user == current_user %>
                                        <%= link_to "削除", image_comment_path(comment.image, comment), method: :delete, class: "btn btn-danger pull-right" %>
                                    <% end %>
                                </td>

                            </tr>
                        </table>
                               
                    <% end %>
                </div>

            </div>

            <div class="col-sm-5">
                <div class="comment-form">

                    <%= form_for [@image, @comment] do |f| %>
                        <div class="row">
                            <div class="col-sm-12">
                                <%= f.text_area :comment, class: "btn btn-block" %>
                            </div>
                        </div>
                        <%= f.submit "コメントする", class: "btn btn-primary pull-right" %>
                    <% end %>
                </div>               
            </div>

        </div>
    </div>
</div>

app/views/images/access.html.erb
<main class="clearfix">

    <%= render 'layouts/search' %>

    <%= render 'layouts/navbar' %>

    <% @images.each.with_index(1) do |image, index| %>

        <div class="float-content">
        	<div class="post-image">
            		<%= link_to image_path(image) do %>
            		<%= attachment_image_tag image, :image, size: "300x300", format: 'jpeg', class: "post-image" %>
                    <% end %>
            </div>

            
            <div class="fct-profile-cont">
                <div class="fct-contents">       
                    <ul>
                        <li class="fct-cont">
                            <% if image.favorited_by?(current_user) %>
                                <%= link_to image_favorites_path(image), method: :delete do %>
                                <i class="fa fa-heart" aria-hidden = "true" style = "color: red;" >
                                    <%= image.favorites.count %>
                                </i>
                                <% end %>                                     
                            <% else %>
                                <%= link_to image_favorites_path(image), method: :post do %>
                                <i class="fa fa-heart-o" aria-hedden = "true" >
                                    <%= image.favorites.count %>
                                </i>
                                <% end %>
                            <% end %>
                        
                                <i class="fa fa-comment-alt" aria-hedden = "true">
                                    <%= image.comments.count %>
                                </i>  

                                <i class="fa fa-eye" aria-hedden = "true">
                                    <%= image.impressions.count %>
                                </i>

                        </li>
                    </ul>
                </div>

                <div class="post-image-title">
                    <%= image.title %>
                </div>

                <div class="acount text-left">
                    <table>
                        <tr>
                            <th class="acount-profile">
                                <td><%= attachment_image_tag(image.user, :profile_image, size: "80x80", class: "img-circle", fallback: "no_image.jpg") %></td>
                            </th>
                        
                            <th class="acount-name">
                                <td><%= image.user.name %></td>
                            </th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    <% end %>  
</main>

app/views/images/favorite.html.erb
<main class="clearfix">

    <%= render 'layouts/search' %>

    <%= render 'layouts/navbar' %>

    <% @images.each do |image| %>

        <div class="float-content">
        	<div class="post-image">
            		<%= link_to image_path(image) do %>
            		<%= attachment_image_tag image, :image, size: "300x300", format: 'jpeg', class: "post-image" %>
                    <% end %>
            </div>

            
           <div class="fct-profile-cont">
                <div class="fct-contents">       
                    <ul>
                        <li class="fct-cont">
                            <% if image.favorited_by?(current_user) %>
                                <%= link_to image_favorites_path(image), method: :delete do %>
                                <i class="fa fa-heart" aria-hidden = "true" style = "color: red;" >
                                    <%= image.favorites.count %>
                                </i>
                                <% end %>                                     
                            <% else %>
                                <%= link_to image_favorites_path(image), method: :post do %>
                                <i class="fa fa-heart-o" aria-hedden = "true" >
                                    <%= image.favorites.count %>
                                </i>
                                <% end %>
                            <% end %>
                        
                                <i class="fa fa-comment-alt" aria-hedden = "true">
                                    <%= image.comments.count %>
                                </i>  

                                <i class="fa fa-eye" aria-hedden = "true">
                                    <%= image.impressions.count %>
                                </i>

                        </li>
                    </ul>
                </div>
            
                <div class="post-image-title">
                    <%= image.title %>
                </div>

                <div class="acount text-left">
                    <table>
                        <tr>
                            <th class="acount-profile">
                                <td><%= attachment_image_tag(image.user, :profile_image, size: "80x80", class: "img-circle", fallback: "no_image.jpg") %></td>
                            </th>
                        
                            <th class="acount-name">
                                <td><%= image.user.name %></td>
                            </th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    <% end %>  
</main>

app/views/images/show.html.erb
<div class="show container">
    <div class="show1 row">
        <h1 class="show-title">投稿詳細</h1>
        <div class="col-sm-7">

    		<div class="post-image1">
        		<%= attachment_image_tag @image, :image, size: "550x450", format: 'jpeg', class: "show-image" %>
            </div>

            <div class="show-profile-cont">
                <div class="fct-contents">       
                    <ul>
                        <li class="fct-cont">
                            <% if @image.favorited_by?(current_user) %>
                                <%= link_to image_favorites_path(@image), method: :delete do %>
                                <i class="fa fa-heart" aria-hidden = "true" style = "color: red;" >
                                    <%= @image.favorites.count %>
                                </i>
                                <% end %>                                     
                            <% else %>
                                <%= link_to image_favorites_path(@image), method: :post do %>
                                <i class="fa fa-heart-o" aria-hedden = "true" >
                                    <%= @image.favorites.count %>
                                </i>
                                <% end %>
                            <% end %>
                        
                                <i class="fa fa-comment-alt" aria-hedden = "true">
                                    <%= @image.comments.count %>
                                </i>  

                                <i class="fa fa-eye" aria-hedden = "true">
                                    <%= @image.impressions.count %>
                                </i>

                        </li>
                    </ul>

                    <div class="acount">
                        <table>
                            <tr>
                                <th class="acount-profile">
                                    <td><%= attachment_image_tag(@image.user, :profile_image, size: "80x80", class: "img-circle", fallback: "no_image.jpg") %></td>
                                </th>
                            
                                <th class="acount-name">
                                    <td><%= @image.user.name %></td>
                                </th>
                            </tr>
                        </table>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-sm-5">

            <h3 class="google-map">GoogleMap</h3>

                <div id= 'map'></div>
                <script type="text/javascript">

                    function initMap() {
                       
                        var test = {lat: <%= @image.latitude %>, lng: <%= @image.longitude %>};
                        var map = new google.maps.Map(document.getElementById('map'), {
                                  zoom: 8, 
                                  center: test
                                  });
                        var transitLayer = new google.maps.TransitLayer();
                        transitLayer.setMap(map);

                        var contentString = '住所：<%= @image.address %>';
                        var infowindow = new google.maps.InfoWindow({
                          content: contentString
                        });

                        var marker = new google.maps.Marker({
                                      position:test,
                                      map: map,
                                      title: contentString
                                     });

                         marker.addListener('click', function() {
                           infowindow.open(map, marker);
                         });
                    }

                </script>

                <script async defer
                    src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
                </script>
                
                <table class="table table_noborder">

                    <tr>
                        <th>キャンプ場名</th>
                            <td class="map-address">
                                <%= @image.address %>
                            </td>
                    </tr>

                    <tr>
                        <th>タイトル</th>
                            <td class="title">
                                <%= @image.title %>
                            </td>
                    </tr>

                    <tr>
                        <th>投稿説明</th>
                            <td class="caption">
                                <%= @image.caption %>
                            </td>
                    </tr>

                </table>

                <% if @image.user == current_user %>
                    <div class="links">
                    	<%= link_to "投稿を編集する", edit_image_path(@image), class: "btn btn-primary btn-block" %> 

                        <%= link_to "投稿を削除する", image_path(@image), class: "btn btn-danger btn-block", method: :delete %>
                    </div>
                <% end %>

        </div>
    </div>

    <div class="border-row">
        <div class="col-lg">
            <hr>
        </div>
    </div>

    <div class="show2 row">
        <div class="comment-contents">
            <h2 class="comment-title">コメント欄</h2>
            <div class="col-sm-7">

                <div class="comment-index">
                    <% @image.comments.each do |comment| %>

                        <table class="comment-index table table-hover table-inverse">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>名前</th>
                                        <th>コメント</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            <%= attachment_image_tag comment.user, :profile_image,  size: "60x60", format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                                        </td>

                                        <td><%= comment.user.name %></td>

                                        <td><%= comment.comment %></td>

                                        <td class="link">
                                            <% if comment.user == current_user %>
                                                <%= link_to "削除", image_comment_path(comment.image, comment), method: :delete, class: "btn btn-danger pull-right" %>
                                            <% end %>
                                        </td>
                                    </tr>
                                </tbody>
                        </table>
                               
                    <% end %>
                </div>

            </div>

            <div class="col-sm-5">
                <div class="comment-form">

                    <%= render "layouts/errors", obj: @image %>

                    <%= form_for [@image, @comment] do |f| %>
                        <div class="row">
                            <div class="col-sm-12">
                                <%= f.text_area :comment, class: "btn btn-block" %>
                            </div>
                        </div>
                        <%= f.submit "コメントする", class: "btn btn-primary pull-right" %>
                    <% end %>
                </div>               
            </div>

        </div>
    </div>
</div>