config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#top'
  get 'home/about' => 'home/about'
  get '/map_request', to: 'images#map', as: 'map/request'
  get 'search' => 'images#index'
  resources :users do
    member do
      get 'check'
      patch 'withdrawl'
    end
  end

  resources :categories, only: [:show]

  resources :inquiries do
    collection do
      get 'confirm'
      get 'thanks'
    end
  end

  resources :images do
    collection do
      get 'favorite'
      get 'access'
    end
    resources :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  namespace :admins do
    get 'home' => 'home#top'
    resources :users

    resources :images do
      resources :comments, only: %i[create destroy]
      resource :favorites, only: %i[create destroy]
    end

    resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  enum is_active: { Available: true, Invalid: false }
  # 有効会員はtrue、退会済み会員はfalse

  def active_for_authentication?
    super && (is_active === 'Available')
  end
  # is_activeが有効の場合は有効会員(ログイン可能)

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_images, through: :favorites, source: :image
  attachment :profile_image

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
    @categories = Category.where(active_status: true)
  end

  def show
    @user = User.find(params[:id])
    @categories = Category.where(active_status: true)
  end

  def edit
    @user = User.find(params[:id])
    @categories = Category.where(active_status: true)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email, :user_id, :acount_status)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    callback_for(:facebook)
  end

  # callback for twitter
  def twitter
    callback_for(:twitter)
  end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: provider.to_s.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @categories = Category.where(active_status: true)
    super
  end

  def create
    @categories = Category.where(active_status: true)
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @categories = Category.where(active_status: true)
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user!, only: %i[edit update]

  def show
    @user = User.find(params[:id])
    @images = current_user.images.all
    @categories = Category.where(active_status: true)
  end

  def edit
    @user = User.find(params[:id])
    @categories = Category.where(active_status: true)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      @categories = Category.where(active_status: true)
      render :edit
    end
  end

  def check
    @user = User.find(params[:id])
  end

  def withdrawl
    @user = User.find(current_user.id)
    # 現在ログインしているユーザーを@userに格納
    @user.acount_status = false
    # acount_statusをfalseに変換
    @user.update(is_active: 'Invalid')
    # updateで登録情報をInvalidに変更
    reset_session
    # sessionIDのresetを行う
    redirect_to root_path
    # 指定されたrootへのpath
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email, :active)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="user-edit-content">

            <%= render "layouts/errors", obj: @user %>

            <h2 class="edit-title">登録内容編集</h2>

            <%= form_for(@user, url: user_path) do |f| %>

                <table> 
                    <tr class="edit-cont">
                        <th class="post-image">
                            <%= attachment_image_tag(@user,:profile_image, size: "100×100", class: "user-edit-image img-circle", fallback: "no_image.jpg") %>
                        </th>
                        <td class="image-field">
                            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: " edit_form" %>
                        </td>
                    </tr>

                    <tr class="edit-cont">
                        <th class="field">
                            <%= f.label :name, "名前", class: "form_label" %>
                        </th>
                        <td>
                          <%= f.text_field :name, autofocus: true, autocomplete:"name", class: "user-edit-btn btn-block form_input" %>
                        </td>
                    </tr>

                    <tr class="edit-cont">
                        <th class="field">
                            <%= f.label :email, "メールアドレス", class: "form_label" %>
                        </th>
                        <td>
                          <%= f.text_field :email, autofocus: true, autocomplete:"email", class: "user-edit-btn btn-block form_input" %>
                        </td>
                    </tr>
                </table>

                <br>

                <div class="actions">
                  <%= f.submit "編集を保存する", class: "btn btn-success btn-lg" %>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="user-content">

            <div class="text-center">
                <h2 class="user-show-title">マイページ</h2>
            </div>

            <div class="col-sm-4">
                <div class="profile-image">
                    <%= attachment_image_tag(current_user,:profile_image, size: "150x150", class: "user-image img-circle", fallback: "no_image.jpg") %>
                </div>
            </div>

            <div class="col-sm-8">
                <table class="table table_noborder">

                    <tr>
                        <th>名前</th>
                        <td class="acount-cont">
                        <%= current_user.name %>
                        </td>
                    </tr>

                    <tr>
                        <th>メールアドレス</th>
                        <td class="acount-cont">
                        <%= current_user.email %>
                        </td>
                    </tr>

                </table>
            </div>

        </div>

        <div class="user-actions">
            <%= link_to "登録内容編集", edit_user_path(@user), class: "btn btn-primary btn-block" %>

            <%= link_to "退会する", withdrawl_user_path(@user.id), class: "btn btn-danger btn-block", method: :patch, data: {confirm: "本当に退会しますか？"} %>
        </div>

    </div>
</div>

    <div class="border-row">
        <hr>
    </div>

    <div class="row">
        <div class="user-index">
            <main class="clearfix">

                <% @images.each do |image| %>

                    <div class="float-content">
                        <div class="post-image">
                                <%= link_to image_path(image) do %>
                                <%= attachment_image_tag image, :image, size: "300x300", format: 'jpeg', class: "post-image" %>
                                <% end %>
                        </div>

                        <div class="fct-profile-cont">
                            <div class="fct-contents">       
                                <ul>
                                    <li class="fct-cont">
                                        <% if image.favorited_by?(current_user) %>
                                            <%= link_to image_favorites_path(image), method: :delete do %>
                                            <i class="fa fa-heart" aria-hidden = "true" style = "color: red;" >
                                                <%= image.favorites.count %>
                                            </i>
                                            <% end %>                                     
                                        <% else %>
                                            <%= link_to image_favorites_path(image), method: :post do %>
                                            <i class="fa fa-heart-o" aria-hedden = "true" >
                                                <%= image.favorites.count %>
                                            </i>
                                            <% end %>
                                        <% end %>
                                    
                                            <i class="fa fa-comment-alt" aria-hedden = "true">
                                                <%= image.comments.count %>
                                            </i>  

                                            <i class="fa fa-eye" aria-hedden = "true">
                                                <%= image.impressions.count %>
                                            </i>

                                    </li>
                                </ul>
                            </div>

                            <div class="post-image-title">
                                <%= image.title %>
                            </div>

                            <div class="acount text-left">
                                <table>
                                    <tr>
                                        <th class="acount-profile">
                                            <td><%= attachment_image_tag(image.user, :profile_image, size: "80x80", class: "img-circle", fallback: "no_image.jpg") %></td>
                                        </th>
                                    
                                        <th class="acount-name">
                                            <td><%= image.user.name %></td>
                                        </th>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                <% end %>
            </main>
        </div>
    </div>