config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#top'
  get 'home/about' => 'home/about'
  get '/map_request', to: 'images#map', as: 'map/request'
  get 'search' => 'images#index'
  resources :users do
    member do
      get 'check'
      patch 'withdrawl'
    end
  end

  resources :categories, only: [:show]

  resources :inquiries do
    collection do
      get 'confirm'
      get 'thanks'
    end
  end

  resources :images do
    collection do
      get 'favorite'
      get 'access'
    end
    resources :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  namespace :admins do
    get 'home' => 'home#top'
    resources :users

    resources :images do
      resources :comments, only: %i[create destroy]
      resource :favorites, only: %i[create destroy]
    end

    resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :images, dependent: :destroy

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  belongs_to :category
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  is_impressionable counter_cache: true
  default_scope -> { order(created_at: :desc) }

  validates :image, presence: true
  validates :title, presence: true
  validates :caption, presence: true
  validates :address, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def favorited_by?(admin)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      Image.where('title LIKE ?', "%#{search}%")
    else
      Image.all
    end
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  attr_accessor :name, :email, :message

  validates :name, presence: { message: '名前を入力してください' }
  validates :email, presence: { message: 'メールアドレスを入力してください' }
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  enum is_active: { Available: true, Invalid: false }
  # 有効会員はtrue、退会済み会員はfalse

  def active_for_authentication?
    super && (is_active === 'Available')
  end
  # is_activeが有効の場合は有効会員(ログイン可能)

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_images, through: :favorites, source: :image
  attachment :profile_image

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
  before_action :authenticate_admin!, only: %i[index create edit update]

  def index
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admins_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.where(active_status: true)
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admins_categories_path
    else
      @categories = Category.where(active_status: true)
      render :edit
    end
  end

  private

  def category_params
    params.require(:category). permit(:name, :active_status, :image_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @user = current_user
    @category = Category.find(params[:id])
    @images = @category.images
    @categories = Category.where(active_status: true)
  end

  private

  def category_params
    params.require(:category). permit(:name, :active_status, :image_id)
  end
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camp_sites_helper.rb
module CampSitesHelper
end

app/helpers/campers_helper.rb
module CampersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admins/categories/edit.html.erb
<div class="container">
    <div class="row">
        <div class="category-edit-cont">

            <h2 class="category-title">カテゴリー編集</h2>

            <%= render 'layouts/errors', obj: @category %>

            <%= form_for (@category), url: admins_category_path do |f| %>

                <div class="field">
                  <%= f.label :name, "ジャンル名", class: "form_label" %>
                  <%= f.text_field :name, class: "form_input" %>
                </div>
                <div class="field brown_txt">
                  <%= f.radio_button :active_status, :true %>
                  <%= f.label :active_status, "有効", {value: :true, style: "display: inline-block;"} %>
                  <%= f.radio_button :active_status, :false %>
                  <%= f.label :active_status, "無効", {value: :false, style: "display: inline-block;"} %>
                </div>

                <div class="category_actions">
                  <%= f.submit "更新する", class: "btn btn-primary" %>
                </div>
            <% end %>

        </div>
    </div>
</div>

app/views/admins/categories/index.html.erb
<div class="container">
    <div class="row">
        <div class="category-content">
            <div class="col-sm-5">
                <h2 class="category-title">カテゴリー登録</h2>
                
                    <div class="form-cont">

                        <%= render 'layouts/errors', obj: @category %>

                        <%= form_for (@category), url: admins_categories_path do |f| %>

                            <div class="field">
                              <%= f.label :name, "ジャンル名", class: "form_label" %>
                              <%= f.text_field :name, class: "form_input" %>
                            </div>

                            <div class="active-status-field">
                              <%= f.radio_button :active_status, :true %>
                              <%= f.label :active_status, "有効", {value: :true, style: "display: inline-block;"} %>
                              <%= f.radio_button :active_status, :false %>
                              <%= f.label :active_status, "無効", {value: :false, style: "display: inline-block;"} %>
                            </div>

                            <div class="category-actions">
                              <%= f.submit "登録", class: "btn btn-primary" %>
                            </div>

                        <% end %>
                    </div>
            </div>

            <br>

            <div class="col-lg-12">
            　  <h2 class="category-title">カテゴリー一覧</h2>
                <table class="table category_table table-hover table-inverse">
                    <thead class="thead">
                      <tr>
                        <th class="brown_txt txts">カテゴリー名</th>
                        <th class="brown_txt txts">ステータス</th>
                        <th colspan="2"></th>
                      </tr>
                    </thead>

                    <tbody>
                        <% @categories.each do |category| %>
                            <tr>
                              <td><%= category.name %></td>
                              <td>
                                <% if category.active_status == true %>
                                <p class="true_txt">有効</p>
                                <% else %>
                                <p class="false_txt">無効</p>
                                <% end %>
                              </td>
                              <td>
                                <%= link_to '編集', edit_admins_category_path(category), class: "edit_btn" %>
                              </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<main class="clearfix">

    <%= render 'layouts/search' %>

    <div class="category_title">
        <%= @category.name %>
    </div>
    
    <%= render 'layouts/navbar' %>

    <% @images.each do |image| %>

        <div class="float-content">
        	<div class="post-image">
            		<%= link_to image_path(image) do %>
            		<%= attachment_image_tag image, :image, size: "300x300", format: 'jpeg', class: "post-image" %>
                    <% end %>
            </div>

            <div class="fct-profile-cont">
                <div class="fct-contents">       
                    <ul>
                        <li class="fct-cont">
                            <% if image.favorited_by?(current_user) %>
                                <%= link_to image_favorites_path(image), method: :delete do %>
                                <i class="fa fa-heart" aria-hidden = "true" style = "color: red;" >
                                    <%= image.favorites.count %>
                                </i>
                                <% end %>                                     
                            <% else %>
                                <%= link_to image_favorites_path(image), method: :post do %>
                                <i class="fa fa-heart-o" aria-hedden = "true" >
                                    <%= image.favorites.count %>
                                </i>
                                <% end %>
                            <% end %>
                        
                                <i class="fa fa-comment-alt" aria-hedden = "true">
                                    <%= image.comments.count %>
                                </i>  

                                <i class="fa fa-eye" aria-hedden = "true">
                                    <%= image.impressions.count %>
                                </i>

                        </li>
                    </ul>
                </div>

                <div class="post-image-title">
                    <%= image.title %>
                </div>

                <div class="acount text-left">
                    <table>
                        <tr>
                            <th class="acount-profile">
                                <td><%= attachment_image_tag(image.user, :profile_image, size: "80x80", class: "img-circle", fallback: "no_image.jpg") %></td>
                            </th>
                        
                            <th class="acount-name">
                                <td><%= image.user.name %></td>
                            </th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    <% end %>
</main>